### ISSUE TITLE
Examples are not synchronized

### ISSUE THREAD

**Issue by PabRod** [DEEPDIP-project/SciML-model-coupling#2]
## Problem

If a fresh clone is made and `make_examples.jl` is run, the following files are updated:

- `examples/Example1.ipynb`
- `examples/Example2.ipynb`
- `examples/Example2.md`

## Solution

- Just update the docs and push them
   - Consider creating a git hook that automates this in the future

In the future we can also consider pushing only the source files, and letting the `.md` and `.ipynb` files be generated via a GitHub action.

**Comment by SCiarella** [comment]
#3 Modifies `make_examples` to guarantee a bit more flexibility.
 
The git hook looks like a fantastic idea, since I think that the use of the `.ipynb` is only as online documentation, while `.jl` files are the way to work locally.

**Comment by PabRod** [comment]
Subtask:

- [ ] Create the abovementioned git hook

**Comment by luisaforozco** [comment]
So we should automate the generation of `Example*.ipynb` and `Example*.md` from `Example*.jl` in a github action.
@PabRod would you like to work on that or assign it to me? Happy with both 😄 but since you are looking at Literate.jl maybe it makes sense that you do it.

**Comment by PabRod** [comment]
I'll be happy to do it. Thanks!

**Comment by PabRod** [comment]
The synchronization problem is now fixed. The generation of the docs via a GitHub action is now part of issue  #12

**Comment by luisaforozco** [comment]
I want to flag that, the automation of the generation os `Example*.ipynb` and `Example*.md` from `Example*.jl` is not mentioned in #12. Can we either keep this issue open or add that to issue #12?

**Comment by PabRod** [comment]
I am aware. Retrospectivelly, I should have split the task into two: packaging and documenting. Lesson learnt for the future.
